#!/usr/bin/python3
#
# makebin.py
#
# Prepares memory initialization files for the Verilog readmemb() functions generated by SpinalHDL.
#
# Input:  A memory image file, hexadecimal, one 32 bit memory location per line.
#
# Output: Four, byte wide, symbol files in binary.
#
import sys

# The memory image file in hexadecimal, one 32 bit location content per line.
bin_file = sys.argv[1]
bin_len  = int(sys.argv[2], 0) * 4
out_file = sys.argv[3]

fi   = open(bin_file, 'rb')
bins = bytearray (fi.read())
fi.close()
if len(bins) < bin_len:
    bins += bytearray(bin_len - len(bins))
else:
    bins  = bins[:bin_len]
for i in range(4):
  fp = open ('%s%d.bin' % (out_file, i), 'w')
  for each in bins[i::4]:
      fp.write(format(each, '08b') + '\n')
  fp.close()
